#! /bin/bash

#
# This script migrates from the eariler opi-sysinfo to
# the newer kgp sysconfig
#

# For testing
#oldconfig="sysinfo.txt"
#newconfig="sysconfig.json"

echo "Check if initial sysconfig setup is needed"

oldconfig="/etc/opi/sysinfo.conf"
newconfig="/etc/kinguard/sysconfig.json"


if [ -e $newconfig ]
then
	echo "Sysconfig already created, terminating"
	exit
fi

if [ ! -e $oldconfig ]
then
	echo "Original config not present, terminating"
	exit
fi

echo "Migrating opi sysinfo to kgp sysconfig"

function vod()
{
	value=$1
	default=$2

	rval=$(sed -n "s/$value=\(.*\)$/\1/ p" <$oldconfig)
	if [  "x$rval" = "x" ]
	then
		rval="$default"
	fi

	printf -v $value "$rval"
}

vod "dnsauthkey" 	"/etc/opi/dnspriv.pem"
vod "unit_id" 		""
vod "ca_path" 		""
vod "opi_name" 		""
vod "domain" 		""
vod "sys_key" 		"/var/opi/etc/syspriv.pem"
vod "dns_key" 		"/etc/opi/dnspriv.pem"
vod "dnsenabled"	"true"

#Fixup for dns
re='^[0-9]+$'
if [[ $dnsenabled =~ $re ]] && [ $dnsenabled -eq 1 ]
then
	echo "Doing dns config fixup"
	dnsenabled="true"
fi

read -d '' template << EOF
{
	"dns" : {
		"dnsauthkey" : "$dns_key",
		"enabled" : $dnsenabled,
		"dnspubkey" : "/etc/opi/dnspub.pem"
	},
	"filesystem" : {
		"luksdevice" : "/dev/mapper/opi",
		"lvmdevice" : "/dev/pool/data",
		"lvmlv" : "data",
		"lvmvg" : "pool",
		"storagemount" : "/var/opi/"
	},
	"hostinfo" : {
		"unitid" : "$unit_id",
		"cafile" : "$ca_path",
		"hostname" : "$opi_name",
		"domain" : "$domain",
		"sysauthkey" : "$sys_key",
		"syscert" : "/etc/opi/opi.cert",
		"syspubkey" : "/var/opi/etc/syspub.pem"
	},
	"webcertificate" : {
		"activecert" : "/etc/opi/web_cert.pem",
		"activekey" : "/etc/opi/web_key.pem",
		"defaultcert" : "/etc/opi/server.cert",
		"defaultkey" : "/etc/opi/dnspriv.pem"
	},
	"backup" : {
		"devicemountpath" : "/mnt/usb"
	},
	"mail" : {
		"localmail" : "/mail/conf/localmail",
		"oprelayserver" : "op-mail.openproducts.com",
		"saslpasswd" : "/mail/conf/sasl_passwd",
		"vdomains" : "/mail/conf/domains",
		"virtualalias" : "/mail/conf/virtual",
		"vmailbox" : "/mail/conf/vmailbox"
	},
	"setup" : {
		"conntesthost" : "http://conntest.op-i.me"
	}
}
EOF

echo "$template" > $newconfig
mv "$oldconfig" "$oldconfig.sav"
