#! /bin/bash

# This is a fixup when /etc/hosts have not been properly updated by
# older software when changing hostname

HFILE=/etc/hosts

if [ ! -e ${HFILE} ]
then
	echo "Missing hosts file??"
	exit 1
fi

HST="$(kgp-sysinfo -p -c hostinfo -k hostname)"
DOM="$(kgp-sysinfo -p -c hostinfo -k domain)"

if [ -z ${HST} ]
then
	echo "Missing hostname in config, terminating"
	exit 0
fi

if [ -z ${DOM} ]
then
	echo "Missing domain in config, terminating"
	exit 0
fi


if grep -q '^127.0.0.1\s*keep$' ${HFILE}
then
	echo "Remove faulty entry in ${HFILE}"
	# Remove faulty line (Not yet)
	sed -i.old -e '/^127.0.0.1\s*keep$/d' ${HFILE}
fi

if grep -q '^127.0.1.1' ${HFILE}
then
	echo "Device have a possibly valid hosts entry, not modifying"
else

	echo "Add KGP device name ${HST}.${DOM} to ${HFILE}"
	echo "127.0.1.1	${HST} ${HST}.{$DOM}" >> ${HFILE}
fi

echo "Done"
