#! /bin/bash

# Installer faulty added keep to mydestination #436
# remove if exists

if [ -e /etc/postfix/main.cf ] && [ -x /usr/sbin/postconf ]
then

	RE="^.*, keep,.*$"
	MD=`postconf -h  mydestination`
	if [[ $MD =~ $RE ]]
	then
		echo "Updating postconf, mydestination"
		postconf -e "mydestination=localhost, localhost.localdomain"
	fi 
fi
