#! /bin/bash

# This is a fixup to update old roundcubemail with static theming #514

FIL="/usr/share/roundcube/config/config.inc.php"
MATCH="\\\$config\\['skin'\\] = \"kgp\";"
LINE="\$config['skin'] = \"kgp\";"
CFG="\$config['skin'] = function_exists(\"getConfigValue\") \\&\\& getConfigValue(\"webapps\",\"theme\") ? getConfigValue(\"webapps\",\"theme\") : \"kgp\";"

if [ -e "$FIL" ]
then
	if grep -Fxq "$LINE" "$FIL"
	then
		sed -i.bak -e "s/$MATCH/$CFG/" "$FIL"
	fi
fi

